all:
        @echo just make install or uninstall

install:
        cp SetLanguage RemoteX AntiAliasing ManageWindows $(DESTDIR)/usr/bin

uninstall:
        rm /usr/bin/SetLanguage /usr/bin/RemoteX /usr/bin/AntiAliasing /usr/bin/ManageWindows
