all:
        @echo just make install or uninstall

install:
        cp SetLanguage SetKeyboard AntiAliasing $(DESTDIR)/usr/bin

uninstall:
        rm /usr/bin/SetLanguage /usr/bin/AntiAliasing /usr/bin/SetKeyboard
